api:
  image: diepdao12892/python-machine-learning-lib:latest
  environment:
    - PYTHONPATH=/code
  command: gunicorn -k tornado -w 2 -b 0.0.0.0:1999 main:app --max-requests 10000 --timeout 7200
  volumes:
    - .:/code
  ports:
    - "1999:1999"
  links:
    - elasticsearch

elasticsearch:
  image: elasticsearch:2.4
  volumes:
    - /root/es-data:/usr/share/elasticsearch/data
